# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33a71212c47e49d608011bdddc47377080495f4f34f346ba0d660ffe82cfa56d869023a915662e067a10fbdf4e462d245389938c0c9fcd9536958193fe09ddf0

test:
  secret_key_base: f39b83fc3cd680378c460246868a15a0719d60ccfb54bd5b44d9232693a930b3e443b558160707cae1290ae2f78684e300d01954d30774c38ba1ee6308cf6912

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
