Challenge.create name: 'Lorem challenge', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus consectetur varius arcu, eget ornare magna pretium molestie. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi euismod maximus lorem in malesuada. Maecenas fermentum malesuada nibh, a sodales tortor sollicitudin ac. Phasellus consequat mauris at lacus scelerisque imperdiet. Pellentesque non pretium nisi. Etiam ultrices auctor dolor in fringilla. Sed ultricies ex a diam aliquet venenatis. Mauris lorem quam, suscipit finibus velit eget, gravida tristique arcu.'

Challenge.create name: 'Chanante challenge', description: 'Chanante ipsum dolor sit amet, droja cartoniano piticli enim cosica páharo con las rodillas in the guanter agazapao, a tope con la maquinaria estoy fatal de lo mío. Zagal atiendee regomello cobete artista nisi síberet, eres un pirámidee, elit gaticos et mangurrián ojete calor, ut. Freshquisimo ullamco pero qué pelazo eiusmod chavalada ut enjuto mojamuto chotera et monetes hueles avinagrado es de traca chiquititantantan bonico del tó.'

Challenge.create name: 'Chiquito challenge', description: 'Lorem fistrum ahorarr fistro ese que llega torpedo diodenoo ese hombree ese pedazo de. Benemeritaar amatomaa qué dise usteer ahorarr diodeno hasta luego Lucas te voy a borrar el cerito quietooor a wan. Amatomaa por la gloria de mi madre a gramenawer de la pradera ahorarr llevame al sircoo está la cosa muy malar apetecan va usté muy cargadoo pecador jarl. Sexuarl pecador hasta luego Lucas pecador. Ese que llega a peich diodeno no puedor quietooor. Te va a hasé pupitaa apetecan pupita ese pedazo de a wan a gramenawer a wan amatomaa a peich ese hombree benemeritaar. Mamaar papaar papaar ese pedazo de tiene musho peligro sexuarl ese pedazo de condemor por la gloria de mi madre. Se calle ustée de la pradera torpedo mamaar fistro a peich ese pedazo de por la gloria de mi madre.'

Challenge.create name: 'Hipster challenge', description: 'Austin chillwave four dollar toast, fashion axe Cosby sweater mustache blog biodiesel roof party paleo 3 wolf moon. Wolf twee letterpress butcher food truck. Ethical quinoa cray pug locavore, letterpress paleo stumptown. Mustache vegan PBR&B cardigan twee, bicycle rights sustainable artisan 90s synth American Apparel Etsy. Tofu Austin tousled kale chips skateboard butcher salvia, tattooed bicycle rights chia typewriter PBR. Heirloom letterpress pickled Schlitz, fashion axe PBR&B Godard leggings photo booth McSweeneys Shoreditch retro four dollar toast whatever food truck. Four dollar toast cliche meditation, stumptown mixtape literally viral polaroid gluten-free bespoke before they sold out.'

(1..50).each do |i|
  Challenge.create name: "Challenge #{i}", description: "Challenge number #{i} description"
end
